firstapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('contactus/', views.contactus2, name='contactus'),
    path('contactusclass/', views.ContactUs.as_view(), name='contactclass'),
    path('signup/', views.RegisterView.as_view(), name='signup'),
    path('login/', views.LoginViewUser.as_view(), name='login'),
    path('logout/', views.LogoutViewUser.as_view(), name='logout'),
    path('signupseller/', views.RegisterViewSeller.as_view(), name='signupseller'),
    path('testsessions/', views.testsessions, name="testsessions"),
    path('listproducts/', views.ListProducts.as_view(), name="listproducts"),
    path('productdetail/<int:pk>/', views.ProductDetail.as_view(), name="productdetail"),
    path('addtocart/<int:id>/', views.addToCart, name="addtocart"),
    path('displaycart/', views.DisplayCart.as_view(), name="displaycart"),
    path('updatecart/<int:pk>/', views.UpdateCart.as_view(), name="updatecart"),
    path('deletefromcart/<int:pk>/', views.DeleteFromCart.as_view(), name="deletefromcart"),
    # path('listproducts/', views.listProducts, name="listproducts"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),

    # change password
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='firstapp/registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name='firstapp/registration/password_change.html',
                                               success_url=reverse_lazy("password_change_done")),
         name='password_change'),

    # Forgot password
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="firstapp/registration/password_reset_form.html",
                                                     success_url=reverse_lazy("password_reset_complete")),
         name="password_reset_confirm"),  # 3
    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="firstapp/registration/password_reset.html",
                                              success_url=reverse_lazy("password_reset_done"),
                                              email_template_name='firstapp/registration/forgot_password_email.html'),
         name="reset_password"),  # 1
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="firstapp/registration/password_reset_sent.html"),
         name="password_reset_done"),  # 2

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="firstapp/registration/password_reset_done.html"),
         name="password_reset_complete"),  # 4

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstapp.urls')),
]

firstapp/models.py
from django.db import models
from django.contrib.auth.models import User, PermissionsMixin
from django.contrib.auth.models import AbstractBaseUser
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from .manager import CustomUserManager
from django.core.validators import RegexValidator
from multiselectfield import MultiSelectField
from django.db.models import Q


# class UserType(models.Model):
#     CUSTOMER = 1
#     SELLER = 2
#     TYPE_CHOICES = (
#         (SELLER, 'Seller'),
#         (CUSTOMER, 'Customer')
#     )
#
#     id = models.PositiveSmallIntegerField(choices=TYPE_CHOICES, primary_key=True)

# def __str__(self):
#     return self.TYPE_CHOICES[]


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    # is_customer = models.BooleanField(default=True)
    # is_seller = models.BooleanField(default=False)

    # type(
    #     (1, 'Seller')
    #     (2, 'Customer')
    # )
    # user_type = models.IntegerField(choices=type, default=1)
    #
    # usertype = models.ManyToManyField(UserType)

    class Types(models.TextChoices):
        SELLER = "Seller", "SELLER"
        CUSTOMER = "Customer", "CUSTOMER"

    default_type = Types.CUSTOMER

    # type = models.CharField(_('Type'), max_length=255, choices=Types.choices, default=default_type)

    type = MultiSelectField(choices=Types.choices, default=[], null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    def save(self, *args, **kwargs):
        if not self.id:
            self.type.append(self.default_type)
        return super().save(*args, **kwargs)


class CustomerAdditional(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    address = models.CharField(max_length=1000)


class SellerAdditional(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    gst = models.CharField(max_length=10)
    warehouse_location = models.CharField(max_length=1000)


class SellerManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(Q(type__contains=CustomUser.Types.SELLER))


class CustomerManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(Q(type__contains=CustomUser.Types.CUSTOMER))


class Seller(CustomUser):
    default_type = CustomUser.Types.SELLER
    objects = SellerManager()

    class Meta:
        proxy = True

    def sell(self):
        print('i can sell')

    @property
    def showAdditional(self):
        return self.selleradditional


class Customer(CustomUser):
    default_type = CustomUser.Types.CUSTOMER
    objects = CustomerManager()

    class Meta:
        proxy = True

    def buy(self):
        print('i can buy')

    @property
    def showAdditional(self):
        return self.customeradditional


class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=255)
    image = models.ImageField(upload_to="firstapp/productimages", default=None, null=True, blank=True)
    price = models.FloatField()

    @classmethod
    def updateprice(cls, product_id, price):
        product = cls.objects.filter(product_id=product_id)
        product = product.first()
        product.price = price
        product.save()
        return product

    @classmethod
    def create(cls, product_name, price):
        product = Product(product_name=product_name, price=price)
        product.save()
        return product

    def __str__(self):
        return self.product_name


class CartManager(models.Manager):
    def create_cart(self, user):
        cart = self.create(user=True)
        return cart


class Cart(models.Model):
    cart_id = models.AutoField(primary_key=True)
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    created_on = models.DateTimeField(default=timezone.now)

    objects = CartManager()


class ProductInCart(models.Model):
    class Meta:
        unique_together = (('cart', 'product'),)

    product_in_cart_id = models.AutoField(primary_key=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()


class Order(models.Model):
    status_choices = (
        (1, 'Not Packed'),
        (2, 'Ready For Shipment'),
        (3, 'Shipped'),
        (4, 'Delivered'),
    )
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    status = models.IntegerField(choices=status_choices, default=1)


class Deal(models.Model):
    user = models.ManyToManyField(CustomUser)
    deal_name = models.CharField(max_length=255)


class Contact(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=10)
    query = models.TextField()

firstapp/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser, Contact, Seller, SellerAdditional, ProductInCart
from django import forms


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email',)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('email',)


class ContactUsForm(forms.ModelForm):
    # email = forms.EmailField(required=True)
    # name = forms.CharField(max_length=100, required=True)
    # phone = forms.CharField(max_length=10, required=True)
    # query = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Contact
        fields = [
            'name',
            'email',
            'phone',
            'query'
        ]


class RegistrationFormSeller(UserCreationForm):
    gst = forms.CharField(max_length=10)
    warehouse_location = forms.CharField(max_length=1000)

    class Meta:
        model = Seller
        fields = [
            'email',
            'name',
            'password1',
            'password2',
            'gst',
            'warehouse_location'
        ]


class RegistrationFormSeller2(forms.ModelForm):
    class Meta:
        model = SellerAdditional
        fields = [
            'gst',
            'warehouse_location'
        ]


class RegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = [
            'email',
            'name',
            'password1',
            'password2'
        ]


class CartForm(forms.ModelForm):
    class Meta:
        model = ProductInCart
        fields = [
            'quantity'
        ]

firstapp/templates/firstapp/basic.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
    {% block css%}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/contactus">Contact Us</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <!--            <form class="d-flex">-->
            <!--                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
            <!--                <button class="btn btn-outline-success" type="submit">Search</button>-->
            <!--            </form>-->
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle dropdownMenuButton" type="button"
                        id="dropdownMenuButton1"
                        data-bs-toggle="dropdown" aria-expanded="false">
                    Account
                </button>
                <ul class="dropdown-menu dropdown-menu-left dropdown-menu-lg-right"
                    aria-labelledby="dropdownMenuButton">
                    <li><a class="dropdown-item" href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a class="dropdown-item" href="{% url 'signupseller' %}">Signup For Seller</a></li>
                    <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                    <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                </ul>
            </div>
        </div>
    </div>
</nav>
{% if messages %}
{% for message in messages %}
<div class="text-center alert alert-{{ message.tags }} alert-dismissible fade show" role="alert"
     style="margin-bottom:0px;">
    {{ message|safe }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}

{% block body %}
{% endblock %}
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
-->
</body>
</html>

firstapp/templates/firstapp/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> </title>
</head>
<body>

</body>
</html>

firstapp/templates/firstapp/contactus.html
{% extends 'firstapp/basic.html' %}
{% load static %}
{% block title %}
{% endblock %}
{% block css %}
{% endblock %}

{% block body %}
<div class="container">
    <form method="POST">{% csrf_token %}
        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" name="name" class="form-control" id="name" placeholder="Your Name">
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">Email address</label>
            <input type="email" class="form-control" id="email" placeholder="name@example.com">
        </div>
        <div class="mb-3">
            <label for="phone" class="form-label">phone No.</label>
            <input type="text" class="form-control" id="phone" placeholder="Your Phone No.">
        </div>
        <div class="mb-3">
            <label for="query" class="form-label">Any Queries</label>
            <textarea class="form-control" id="query" rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>

    </form>
</div>
{% endblock %}

firstapp/templates/firstapp/contactus2.html
{% extends 'firstapp/basic.html' %}
{% load static %}
{% block title %}
{% endblock %}
{% block css %}
{% endblock %}

{% block body %}
<div class="container">
    <form method="POST">{% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Submit</button>

    </form>
</div>
{% endblock %}

firstapp/templates/firstapp/displaycart.html
{% extends 'firstapp/basic.html' %}
{% load static %}
{% load myfilters %}
{% block title %}
{% endblock %}
{% block css %}
<style>
  .main-area {
    padding-left: 20px;
    padding-right: 20px;
    padding-top: 0px;
    background-color: #f8f9fa;
  }

  .product-cards {
    background-color: white;
    padding: 10px;
  }

  .btn-primary {
    margin: 10px;
  }
</style>
{% endblock %}

{% block body%}
<div class="main-area">
  <div class="product-cards">
    <h1 style="text-align:center;">CART</h1>

    {% for i in cart %}
    <div class="row featurette">
      <div class="col-md-2">
        <img src="/media/{{i.product.image}}" class="card-img-top" alt="...">
      </div>
      <div class="col-md-7">
        <h2 class="featurette-heading">{{i.product.product_name}}</h2>
        <p class="lead">Rs. {{i.product.price}}</p>
        <p class="lead">Quantity- {{i.quantity}}</p>
        <form method="POST" action="{% url 'updatecart' pk=i.product_in_cart_id %}">{% csrf_token %}
          <input type="text" id="id_quantity" name="quantity">
          <button class="btn btn-primary" type="submit">Update Quantity</button>
        </form>
        <form method="POST" action="{% url 'deletefromcart' pk=i.product_in_cart_id %}">{% csrf_token %}
          <button class="btn btn-primary" type="submit">Delete</button>
        </form>
      </div>

    </div>
    <hr>
    {% empty %}
    <h4>Empty Cart</h4>
    {% endfor %}

    <form method="POST" action="/payment/">{% csrf_token %}
    <button class="btn btn-primary" type="submit">Proceed for Payment</button>
    </form>
  </div>

</div>
{% endblock %}

firstapp/templates/firstapp/listproducts.html
{% extends 'firstapp/basic.html' %}
{% load static %}
{% load myfilters %}
{% block title %}
{% endblock %}
{% block css %}
<style>
    .main-area {
        padding-left: 20px;
        padding-right: 20px;
        background-color: white;

    }
    .product-cards{
        background-color: white;
        padding: 10px;

    }
</style>
{% endblock %}
{% block body %}
<div class="main-area">
    <div class="product-cards">
        <div class="row row-cols-1 row-cols-md-4 g-4">
            {% for i in product %}
            <div class="col">
                <div class="card h-100">
                    <img src="/media/{{i.image}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'productdetail' pk=i.pk %}">{{i.product_name}}</a>
                        </h5>
                        <p class="card-text">{{i.price}}</p>
                    </div>
                    <a class="btn btn-primary" href="{% url 'addtocart' id=i.product_id %}">Add To Cart</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

firstapp/templates/firstapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

firstapp/templates/firstapp/productdetail.html
{% extends 'firstapp/basic.html' %}
{% load static %}
{% load myfilters %}
{% block title %}
{% endblock %}
{% block css %}
<style>
    .main-area {
        padding-left: 20px;
        padding-right: 20px;
        padding-top: 0px;
        background-color: #f8f9fa;
    }

    .product-cards {
        background-color: white;
        padding: 10px;
    }
    .btn-primary{
        margin: 10px;
    }
</style>
{% endblock %}

{% block body%}
<div class="main-area">
    <div class="product-cards">
        <div class="row featurette">
            <div class="col-md-5">
                <img src="/media/{{product.image}}" class="card-img-top" alt="...">

            </div>
            <div class="col-md-7">
                <h2 class="featurette-heading">{{product.product_name}}</h2>
                <p class="lead">Rs. {{product.price}}</p>
                <a class="btn btn-primary" href="{% url 'addtocart' id=product.product_id %}">Add To Cart</a>
            </div>

        </div>
    </div>

</div>
{% endblock %}

firstapp/templates/firstapp/register.html
{% extends 'firstapp/basic.html' %}
{% load static %}
{% load myfilters %}
{% block title %}
{% endblock %}
{% block css %}
<style>
    body {
        background-color: #e3dada;
    }

    .main-area {
        display: flex;
        align-items: center;
    }

    .register-form {
        width: 100%;
        max-width: 500px;
        margin: auto;
        margin-top: 40px;
        padding: 20px;
        background-color: #fff;
        border-top: 5px solid #2BA977;
        border-radius: 5px;
    }

    .mainheading {
        text-align: center;
    }

    .errorlist {
        color: #ff0000;
    }

    .signup-button {
        background-color: #2BA977;
        border-color: #2BA977;
    }

    .signup-button:hover {
        background-color: #2BA977;
        border-color: #2BA977;
    }

    .signup-button:focus {
        background-color: #2BA977;
        border-color: #2BA977;
    }
</style>
{% endblock %}
{% block body %}
<form method="POST">{% csrf_token %}
    <div class="main-area">
        <div class="register-form">
            <!--    {{form.as_p}}-->
            {{ form.non_field_errors }}

            <h2 class="mainheading">E-Commerce</h2>
            <h4 class="mainheading">Sign Up</h4>

            <label for="id_email" class="login-labels">Email Address*</label>
            {{ form.email.errors }}
            {{ form.email|addclass:'form-control'|addplaceholder:'Your Email' }}

            <label for="id_name" class="login-labels">Name*</label>
            {{ form.name.errors }}
            {{ form.name|addclass:'form-control'|addplaceholder:'Your Name' }}


            <label for="id_password1" class="login-labels">Password*</label>
            {{ form.password1.errors }}
            {{ form.password1|addclass:'form-control'|addplaceholder:'Your Password' }}

            <label for="password2" class="login-labels">Password Confirmation*</label>
            {{ form.password2.errors }}
            {{ form.password2|addclass:'form-control'|addplaceholder:'Your Password' }}

            <label for="id_gst" class="login-labels">GST*</label>
            {{ form.gst.errors }}
            {{ form.gst|addclass:'form-control'|addplaceholder:'GST' }}

            <label for="id_warehouse_location" class="login-labels">Warehouse Location*</label>
            {{ form.warehouse_location.errors }}
            {{ form.warehouse_location|addclass:'form-control'|addplaceholder:'Warehouse Location' }}
            <br>

            <button type="submit" class="btn btn-primary btn-lg signup-button">Signup</button>

        </div>
    </div>
</form>

{% endblock %}

firstapp/templates/firstapp/registerbasicuser.html
{% extends 'firstapp/basic.html' %}
{% load static %}
{% load myfilters %}
{% block title %}
{% endblock %}
{% block css %}
<style>
    body {
        background-color: #e3dada;
    }

    .main-area {
        display: flex;
        align-items: center;
    }

    .register-form {
        width: 100%;
        max-width: 500px;
        margin: auto;
        margin-top: 40px;
        padding: 20px;
        background-color: #fff;
        border-top: 5px solid #2BA977;
        border-radius: 5px;
    }

    .mainheading {
        text-align: center;
    }

    .errorlist {
        color: #ff0000;
    }

    .signup-button {
        background-color: #2BA977;
        border-color: #2BA977;
    }

    .signup-button:hover {
        background-color: #2BA977;
        border-color: #2BA977;
    }

    .signup-button:focus {
        background-color: #2BA977;
        border-color: #2BA977;
    }
</style>
{% endblock %}
{% block body %}
<form method="POST">{% csrf_token %}
    <div class="main-area">
        <div class="register-form">
            <!--    {{form.as_p}}-->
            {{ form.non_field_errors }}

            <h2 class="mainheading">E-Commerce</h2>
            <h4 class="mainheading">Sign Up</h4>

            <label for="id_email" class="login-labels">Email Address*</label>
            {{ form.email.errors }}
            {{ form.email|addclass:'form-control'|addplaceholder:'Your Email' }}

            <label for="id_name" class="login-labels">Name*</label>
            {{ form.name.errors }}
            {{ form.name|addclass:'form-control'|addplaceholder:'Your Name' }}


            <label for="id_password1" class="login-labels">Password*</label>
            {{ form.password1.errors }}
            {{ form.password1|addclass:'form-control'|addplaceholder:'Your Password' }}

            <label for="password2" class="login-labels">Password Confirmation*</label>
            {{ form.password2.errors }}
            {{ form.password2|addclass:'form-control'|addplaceholder:'Your Password' }}

            <br>

            <button type="submit" class="btn btn-primary btn-lg signup-button">Signup</button>

        </div>
    </div>
</form>

{% endblock %}

firstapp/templates/firstapp/registerseller.html
{% extends 'firstapp/basic.html' %}
{% load static %}
{% load myfilters %}
{% block title %}
{% endblock %}
{% block css %}
<style>
    body {
        background-color: #e3dada;
    }

    .main-area {
        display: flex;
        align-items: center;
    }

    .register-form {
        width: 100%;
        max-width: 500px;
        margin: auto;
        margin-top: 40px;
        padding: 20px;
        background-color: #fff;
        border-top: 5px solid #2BA977;
        border-radius: 5px;
    }

    .mainheading {
        text-align: center;
    }

    .errorlist {
        color: #ff0000;
    }

    .signup-button {
        background-color: #2BA977;
        border-color: #2BA977;
    }

    .signup-button:hover {
        background-color: #2BA977;
        border-color: #2BA977;
    }

    .signup-button:focus {
        background-color: #2BA977;
        border-color: #2BA977;
    }
</style>
{% endblock %}
{% block body %}
<form method="POST">{% csrf_token %}
    <div class="main-area">
        <div class="register-form">
            <!--    {{form.as_p}}-->
            {{ form.non_field_errors }}

            <h2 class="mainheading">E-Commerce</h2>
            <h4 class="mainheading">Sign Up</h4>

            <label for="id_gst" class="login-labels">GST*</label>
            {{ form.gst.errors }}
            {{ form.gst|addclass:'form-control'|addplaceholder:'GST' }}

            <label for="id_warehouse_location" class="login-labels">Warehouse Location*</label>
            {{ form.warehouse_location.errors }}
            {{ form.warehouse_location|addclass:'form-control'|addplaceholder:'Warehouse Location' }}
            <br>

            <button type="submit" class="btn btn-primary btn-lg signup-button">Signup</button>

        </div>
    </div>
</form>

{% endblock %}

firstapp/templates/firstapp/sessiontesting.html
{% extends 'firstapp/basic.html' %}
{% load static %}
{% block title %}
{% endblock %}
{% block css %}
{% endblock %}

{% block body%}
{% if user.is_authenticated %}
<h1>{{user.name}}</h1>
{% endif %}
{{ request.session.test }}
{{ request.session.test2 }}
{% endblock %}